language: minimal
services:
  - docker

install:
  - make build

stages:
  - fmt
  - test
  - help

jobs:
  include:
    - stage: fmt
      script: make test-fmt
    - stage: test
      script: make test
    - stage: help
      script: make test-help
