language: minimal
services:
  - docker

install:
  - docker build -t kostyaesmukov/smtp_to_telegram .

stages:
  - fmt
  - dep_check
  - test
  - help

jobs:
  include:
    - stage: fmt
      script:
        - docker run --rm --entrypoint=sh kostyaesmukov/smtp_to_telegram
            -c "test -z `go fmt`"
    - stage: dep_check
      script:
        - docker run --rm --entrypoint=sh kostyaesmukov/smtp_to_telegram
            -c "dep check"
    - stage: test
      script:
        # go 1.11 wants gcc, `CGO_ENABLED=0` fixes that.
        # See: https://github.com/golang/go/issues/26988
        - docker run --rm --entrypoint=sh kostyaesmukov/smtp_to_telegram
            -c "CGO_ENABLED=0 go test"
    - stage: help
      script:
        - docker run --rm kostyaesmukov/smtp_to_telegram
            --help 2>&1 | grep -q 'A small program which listens'
